### ISSUE TITLE
randomize locations for lon/lat coordinates that are the same

### ISSUE THREAD

**Issue by skrivulskaya** [skrivulskaya/badin-bible-rural-md#1]
It occurred to me that randomization might be not as straight-forward as with the eloping ministers, since I have manually fixed a few instances of geotagged lon/lat coordinates. So the randomization check would need to make sure to check both of those columns (instead of the PlottedLocation) column before to deciding whether to randomize the location for people who are at the same place. Let me know if this is confusing.

**Comment by msisk1** [comment]
Added it. I left it at a fairly low distance, that can be modified in the code easily.
