### ISSUE TITLE
fix selection filters

### ISSUE THREAD

**Issue by skrivulskaya** [skrivulskaya/badin-bible-rural-md#9]
Currently, "Confirmed Slave Owners" and "Priests" filters are not properly reactive. Ideally, we'll change those to either RadioButtons or a drop-down menu with options that also include data in columns about runaway slaves, slaves who sued for freedom, manumitted slaves, and slaves who were freed by owners, which are all in the updated geocoded file.

(I also can't figure out how to get the filters to nest in a prettier manner under the "Map" menuItem feature or how to get each of the menuItems to expand to reveal sub-menus)

Also: Please add a new Plantation Size filter. The new PlantationSize column in the geocoded file currently divides subscribers by the number of people they owned. I'm guessing the big plantation owners will be situated more along the river, whereas others will be more scattered.

**Comment by msisk1** [comment]
Done, the blank ones need a name though.
